default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: give_lively_interview_development


test:
  <<: *default
  database: give_lively_interview_test

production:
  <<: *default
  database: give_lively_interview_production
  username: give_lively_interview
  password: <%= ENV['DATABASE_PASSWORD'] %>
